# Generated by Django 3.1.7 on 2021-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='journal',
            name='additional_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
