# Generated by Django 3.1.7 on 2021-03-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210317_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.product'),
        ),
    ]
