# Generated by Django 3.1.7 on 2021-05-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_companyindustry'),
        ('books', '0006_auto_20210330_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.expensecategory'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.industry'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.product'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.subcategory'),
        ),
    ]
