# Generated by Django 3.1.7 on 2021-05-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210506_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.expensecategory'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.product'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.subcategory'),
        ),
    ]
