# Generated by Django 3.1.7 on 2021-05-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_companyindustry'),
        ('books', '0010_auto_20210506_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.industry'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.product'),
        ),
    ]
