# Generated by Django 3.1.7 on 2021-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210506_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('Goods', 'Barang'), ('Services', 'Jasa')], default='Goods', max_length=50, null=True),
        ),
    ]
