# Generated by Django 3.1.7 on 2021-05-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20210517_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('Barang', 'Barang'), ('Jasa', 'Jasa')], default='Barang', max_length=50),
        ),
    ]
