# Generated by Django 3.1.7 on 2021-03-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210315_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.industry'),
        ),
    ]
