# Generated by Django 3.1.7 on 2021-03-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210315_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyIndustry',
        ),
    ]
