# Generated by Django 3.1.7 on 2021-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='light_dark_mode',
            field=models.CharField(default='Dark', max_length=55),
        ),
    ]
