# Generated by Django 3.1.7 on 2021-05-15 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210514_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='light_dark_mode',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light')], default='Dark', max_length=55),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
